a.out:head.o addevent.o delete.o find.o printcal.o save.o upcomingevent.o viewevent.o sync.o
	cc head.o addevent.o delete.o find.o printcal.o save.o upcomingevent.o viewevent.o sync.o
head.o:head.c
	cc -c head.c
addevent.o:addevent.c
	cc -c addevent.c
delete.o:delete.c
	cc -c delete.c
find.o:find.c
	cc -c find.c
printcal.o:printcal.c
	cc -c printcal.c
save.o:save.c
	cc -c save.c
upcomingevent.o:upcomingevent.c
	cc -c upcomingevent.c
viewevent.o:viewevent.c
	cc -c viewevent.c
sync.o:sync.c
	cc -c sync.c

